version: '3.7'

services:
  dev:
    container_name: nestjs-elections-api_dev
    build:
      context: .
      target: development
      dockerfile: .docker/Dockerfile
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
    restart: unless-stopped

  prod:
    container_name: nestjs-elections-api_prod
    build:
      context: .
      target: production
      dockerfile: .docker/Dockerfile
    command: npm run start:prod
    ports:
      - ${APP_PORT}:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
