FROM node:17.8.0-alpine3.15 as development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=development

COPY . .

RUN npm run build

FROM node:17.8.0-alpine3.15 as production

ARG NODE_ENV=production
ENV NODE_EN=${NODE_ENV}

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]
